
import { Student, FinancialRequest, Donation, RequestCategory, UrgencyLevel } from './types';

export const mockUsers: Student[] = [
  {
    id: 'u1',
    name: 'Ankita Das',
    email: 'student@university.edu',
    university: 'Global Institute of Technology',
    studentId: 'GIT-2024-001',
    passcode: 'student123',
    verificationStatus: 'VERIFIED',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Ankita&backgroundColor=d1fae5&shape1Color=059669',
    role: 'STUDENT'
  },
  {
    id: 'u_admin',
    name: 'Admin Overseer',
    email: 'admin@access.edu',
    university: 'Institutional Audit',
    studentId: 'ADMIN-001',
    passcode: 'admin123',
    verificationStatus: 'VERIFIED',
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Admin&backgroundColor=064e3b&shape1Color=ffffff',
    role: 'ADMIN'
  }
];

export const mockRequests: FinancialRequest[] = [
  {
    id: 'req_1',
    studentId: 'u2',
    studentName: 'Rahul Mehra',
    title: 'Final Semester Hostel & Mess Fees',
    category: RequestCategory.HOUSING,
    imageUrl: 'https://images.unsplash.com/photo-1555854817-5b2260d50c47?q=80&w=800&auto=format&fit=crop', 
    description: 'Sudden financial crisis at home due to crop loss. Need support to clear the final semester mess and hostel dues to receive my marksheet.',
    requestedAmount: 42000,
    raisedAmount: 15200,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 400000000).toISOString(),
  },
  {
    id: 'req_2',
    studentId: 'u3',
    studentName: 'Priya Sharma',
    title: 'Critical Laptop Repair for Project',
    category: RequestCategory.BOOKS,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=800&auto=format&fit=crop',
    description: 'My laptop screen cracked during transit. As a CS student, I cannot complete my final year capstone without it. Repair estimate is ₹8,500.',
    requestedAmount: 8500,
    raisedAmount: 4000,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'req_pending_1',
    studentId: 'u7',
    studentName: 'Arjun K.',
    title: 'Backlog Exam Fees',
    category: RequestCategory.FEES,
    imageUrl: 'https://images.unsplash.com/photo-1454165833767-017546954de4?q=80&w=800&auto=format&fit=crop',
    description: 'Need to clear the registration fees for 3 backlog papers to be eligible for campus placements next week.',
    requestedAmount: 4500,
    raisedAmount: 0,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: true,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'req_frivolous_1',
    studentId: 'u_friv_1',
    studentName: 'John D.',
    title: 'Upgrade to Latest iPhone Pro',
    category: RequestCategory.OTHER,
    imageUrl: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=800&auto=format&fit=crop',
    description: 'I really need the new iPhone 15 Pro for better selfies and group photos. My current one is 2 years old and feels slow.',
    requestedAmount: 120000,
    raisedAmount: 0,
    urgency: UrgencyLevel.LOW,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 50000).toISOString(),
  },
  {
    id: 'req_frivolous_2',
    studentId: 'u_friv_2',
    studentName: 'Sarah M.',
    title: 'Designer Sneakers for Freshers Party',
    category: RequestCategory.OTHER,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
    description: 'The annual freshers party is coming up and I want to make a big impression. Need help buying a pair of limited edition sneakers.',
    requestedAmount: 25000,
    raisedAmount: 0,
    urgency: UrgencyLevel.LOW,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 20000).toISOString(),
  },
  {
    id: 'req_pending_2',
    studentId: 'u8',
    studentName: 'Sneha L.',
    title: 'Emergency Wisdom Tooth Surgery',
    category: RequestCategory.MEDICAL,
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=800&auto=format&fit=crop',
    description: 'Severe infection in lower molar. Need extraction as advised by campus health center. Parents currently facing financial hardship.',
    requestedAmount: 6200,
    raisedAmount: 0,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date().toISOString(),
  }
];

export const mockDonations: Donation[] = [];
