import { Student, FinancialRequest, Donation, UrgencyLevel, RequestCategory } from './types';

export const mockUsers: Student[] = [
  {
    id: 'u1',
    name: 'Ankita Das',
    email: 'ankita.24ucs001@nita.ac.in',
    university: 'NIT Agartala',
    studentId: '24UCS001',
    isVerified: true,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Ankita&backgroundColor=d1fae5&shape1Color=059669',
    role: 'STUDENT'
  },
  {
    id: 'u_admin',
    name: 'Admin Overseer',
    email: 'registrar@iiita.ac.in',
    university: 'IIIT Agartala Admin',
    isVerified: true,
    avatar: 'https://api.dicebear.com/7.x/shapes/svg?seed=Admin&backgroundColor=064e3b&shape1Color=ffffff',
    role: 'ADMIN'
  }
];

export const mockRequests: FinancialRequest[] = [
  // --- HOUSING / HOSTEL FEES (3 Cards) ---
  {
    id: 'r_hostel_1',
    studentId: 'u2',
    studentName: 'Rahul Mehra',
    studentEmail: 'rahul.23uec045@nita.ac.in',
    studentIdCardNumber: '23UEC045',
    title: 'Final Semester Hostel & Mess Fees',
    category: RequestCategory.HOUSING,
    imageUrl: 'https://images.unsplash.com/photo-1555854817-5b2260d50c47?q=80&w=1000&auto=format&fit=crop', 
    description: 'Sudden financial crisis at home due to crop loss. Need support to clear the final semester mess and hostel dues to receive my marksheet.',
    requestedAmount: 42000,
    raisedAmount: 15200,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r_hostel_2',
    studentId: 'u3',
    studentName: 'Sanya Malhotra',
    studentEmail: 'sanya.22ume112@nita.ac.in',
    studentIdCardNumber: '22UME112',
    title: 'Hostel Registration & Security Deposit',
    category: RequestCategory.HOUSING,
    imageUrl: 'https://images.unsplash.com/photo-1626178732047-394935b5c9a9?q=80&w=1000&auto=format&fit=crop', 
    description: 'First-year student from a humble background. The initial hostel deposit and room fee are exceeding our current savings.',
    requestedAmount: 18500,
    raisedAmount: 9100,
    urgency: UrgencyLevel.MEDIUM,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'r_hostel_3',
    studentId: 'u4',
    studentName: 'Amit Singh',
    studentEmail: 'amit.25uee012@iiita.ac.in',
    studentIdCardNumber: '25UEE012',
    title: 'Overdue Mess Charges Assistance',
    category: RequestCategory.HOUSING,
    imageUrl: 'https://images.unsplash.com/photo-1567529684892-09290a1b2d05?q=80&w=1000&auto=format&fit=crop', 
    description: 'I work a part-time job, but my salary was delayed this month. Need to clear mess bills to avoid late penalty.',
    requestedAmount: 6500,
    raisedAmount: 4200,
    urgency: UrgencyLevel.LOW,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },

  // --- MEDICAL (3 Cards) ---
  {
    id: 'r_med_1',
    studentId: 'u5',
    studentName: 'Arjun Verma',
    studentEmail: 'arjun.25uce009@iiita.ac.in',
    studentIdCardNumber: '25UCE009',
    title: 'Emergency Eye Surgery Consultation',
    category: RequestCategory.MEDICAL,
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1000&auto=format&fit=crop', 
    description: 'Diagnosed with a retinal issue. Need urgent consultation and preliminary treatment at the state eye hospital.',
    requestedAmount: 12200,
    raisedAmount: 8800,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r_med_2',
    studentId: 'u6',
    studentName: 'Anonymous Peer',
    studentEmail: 'peer.24uch077@nita.ac.in',
    studentIdCardNumber: '24UCH077',
    title: 'Wisdom Tooth Extraction & Meds',
    category: RequestCategory.MEDICAL,
    imageUrl: 'https://images.unsplash.com/photo-1588776814546-1ffce47267a5?q=80&w=1000&auto=format&fit=crop', 
    description: 'Chronic pain making it impossible to study for mid-terms. Need surgical extraction for two impacted teeth.',
    requestedAmount: 9500,
    raisedAmount: 3000,
    urgency: UrgencyLevel.MEDIUM,
    isAnonymous: true,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'r_med_3',
    studentId: 'u7',
    studentName: 'Sneha Roy',
    studentEmail: 'sneha.23ucs102@nita.ac.in',
    studentIdCardNumber: '23UCS102',
    title: 'Prescription Glasses Replacement',
    category: RequestCategory.MEDICAL,
    imageUrl: 'https://images.unsplash.com/photo-1511732351157-1875f3232266?q=80&w=1000&auto=format&fit=crop', 
    description: 'Broke my high-power prescription glasses during a lab session. Cannot attend classes without a replacement.',
    requestedAmount: 4800,
    raisedAmount: 2100,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
  },

  // --- BOOKS / EXAMS (3 Cards) ---
  {
    id: 'r_books_1',
    studentId: 'u8',
    studentName: 'Priya Das',
    studentEmail: 'priya.23ucs031@iiita.ac.in',
    studentIdCardNumber: '23UCS031',
    title: 'GATE 2025 Study Materials',
    category: RequestCategory.BOOKS,
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1000&auto=format&fit=crop', 
    description: 'Aspiring for higher studies. Need support to buy a standard test series and technical books for Civil Engineering.',
    requestedAmount: 7500,
    raisedAmount: 1200,
    urgency: UrgencyLevel.LOW,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'r_books_2',
    studentId: 'u9',
    studentName: 'Kabir Singh',
    studentEmail: 'kabir.22uce055@nita.ac.in',
    studentIdCardNumber: '22UCE055',
    title: 'Professional Drafting Set for Lab',
    category: RequestCategory.BOOKS,
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592dea58ef21?q=80&w=1000&auto=format&fit=crop', 
    description: 'Mandatory drafting toolkit for the final year design project. High cost for high-precision tools.',
    requestedAmount: 11200,
    raisedAmount: 5500,
    urgency: UrgencyLevel.MEDIUM,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'r_books_3',
    studentId: 'u10',
    studentName: 'Ritika Sen',
    studentEmail: 'ritika.24uee022@iiita.ac.in',
    studentIdCardNumber: '24UEE022',
    title: 'Core Semiconductor Textbooks',
    category: RequestCategory.BOOKS,
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=1000&auto=format&fit=crop', 
    description: 'Library copies are always checked out. I need these books for my upcoming end-term examinations.',
    requestedAmount: 3200,
    raisedAmount: 1800,
    urgency: UrgencyLevel.MEDIUM,
    isAnonymous: false,
    status: 'APPROVED',
    createdAt: new Date().toISOString(),
  },

  // --- ADMIN PENDING QUEUE (3 Cards: 1 Invalid, 2 Valid) ---
  {
    id: 'r_pending_valid_1',
    studentId: 'u11',
    studentName: 'Vikram Sharma',
    studentEmail: 'vikram.23ume012@iiita.ac.in',
    studentIdCardNumber: '23UME012',
    title: 'Emergency Mid-Semester Fee Hike',
    category: RequestCategory.FEES,
    imageUrl: 'https://images.unsplash.com/photo-1554224155-1696413565d3?q=80&w=1000&auto=format&fit=crop', 
    description: 'The institute announced a sudden adjustment in the laboratory fees. I need support to bridge this gap to remain enrolled.',
    requestedAmount: 15000,
    raisedAmount: 0,
    urgency: UrgencyLevel.HIGH,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'r_pending_valid_2',
    studentId: 'u12',
    studentName: 'Deepak Roy',
    studentEmail: 'deepak.24uce011@nita.ac.in',
    studentIdCardNumber: '24UCE011',
    title: 'Laptop Battery Replacement',
    category: RequestCategory.OTHER,
    imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop', 
    description: 'My laptop battery has failed, and I can only use it while plugged in, which is impossible during labs and library sessions.',
    requestedAmount: 5200,
    raisedAmount: 0,
    urgency: UrgencyLevel.MEDIUM,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'r_pending_invalid_1',
    studentId: 'u_fake',
    studentName: 'Suspicious Profile',
    studentEmail: 'fast.money@gmail.com', // NOT A UNI EMAIL
    studentIdCardNumber: 'NO-CARD-ID',
    title: 'Premium Gaming Laptop Upgrade',
    category: RequestCategory.OTHER,
    imageUrl: 'https://images.unsplash.com/photo-1605898960710-99432e181281?q=80&w=1000&auto=format&fit=crop', 
    description: 'I want to buy the latest ROG laptop to play games after college. It will help my "hand-eye coordination". Very urgent!',
    requestedAmount: 95000,
    raisedAmount: 0,
    urgency: UrgencyLevel.LOW,
    isAnonymous: false,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  }
];

export const mockDonations: Donation[] = [];